Repository GenomicMedLab/dgipy, pull requests merged in 2024-11, with the labels that each got.

#81 style: update ruff settings
  pyproject.toml
Labels: priority:low

#80 build!: require python 3.11-13
  .github/workflows/checks.yaml
  pyproject.toml
Labels: priority:low

#75 feat: add cytoscape export
  src/dgipy/graph_app.py
Labels: enhancement, priority:low

#78 cicd: update precommit hooks + run checks
  .github/workflows/checks.yaml
  .pre-commit-config.yaml
Labels: priority:low

#76 chore: update gitignore
  .gitignore
Labels: priority:low

#77 chore: add stale action
  .github/workflows/stale.yaml
Labels: priority:low

#83 cicd: fix GH action file
  .github/workflows/checks.yaml
  src/dgipy/graph_app.py
  tests/test_graph_app.py
Labels: priority:high, stale

#84 feat: declare dgipy client in request header
  src/dgipy/dgidb.py
Labels: priority:high
